const app=document.getElementById("app");
function layout(content,eyebrow="TMS"){return `<div class="shell"><header class="topbar"><div class="brand"><span class="brand-mark">T</span><span>${eyebrow}</span></div><span class="mini-label">TRAINING & LEARNING</span></header>${content}<footer>Training Management System • Versi 1.0</footer></div>`}
function render(){if(state.screen==="home")return renderHome();if(state.screen==="identity")return renderIdentity();if(state.screen==="learning")return renderLearning();if(state.screen==="result")return renderResult();state.screen="home";renderHome()}
function renderHome(){app.innerHTML=layout(`<section class="hero"><div class="hero-copy"><div class="pill">● ONLINE TRAINING</div><h1>Belajar singkat.<br><em>Paham lebih cepat.</em></h1><p>Materi, gambar, video, dan evaluasi dalam satu pengalaman belajar yang sederhana dan interaktif.</p><button class="primary" onclick="goIdentity()">Mulai Training <span>→</span></button></div><div class="hero-card"><div class="card-icon">▣</div><div><strong>${escapeHtml(TRAINING.title)}</strong><small>${escapeHtml(TRAINING.subtitle)}</small></div><div class="stats"><span><b>${getMaterialCount()}</b>Materi</span><span><b>${getQuestionCount()}</b>Soal</span><span><b>${escapeHtml(TRAINING.duration||"-")}</b>Durasi</span></div><div class="slide-count">${getSlides().length} slide pembelajaran</div></div></section><section class="feature-row"><div><span>01</span><b>Pelajari materi</b><p>Materi disajikan secara bertahap melalui slide yang interaktif.</p></div><div><span>02</span><b>Tonton & pahami</b><p>Materi dapat dilengkapi gambar, grafik, dan video.</p></div><div><span>03</span><b>Kerjakan evaluasi</b><p>Soal dapat ditempatkan di antara materi sesuai alur training.</p></div></section>`)}
function renderIdentity(){app.innerHTML=layout(`<section class="form-page"><div class="section-kicker">01 / IDENTITAS PESERTA</div><h2>Sebelum mulai,<br>kenalkan diri dulu.</h2><p class="muted">Data ini digunakan untuk mencatat hasil training.</p><form onsubmit="startTraining(event)" class="identity-form"><label>Nama lengkap<input id="name" required placeholder="Contoh: Ahmad Yani"></label><label>Email <span class="optional">(opsional)</span><input id="email" type="email" placeholder="nama@perusahaan.com"></label><button class="primary full" type="submit">Mulai Training <span>→</span></button></form></section>`)}
function goIdentity(){state.screen="identity";saveState();render()}
function startTraining(e){e.preventDefault();state.participant.name=document.getElementById("name").value.trim();state.participant.email=document.getElementById("email").value.trim();state.currentSlide=0;state.answers={};state.isSaving=false;state.screen="learning";saveState();render()}
function renderLearning(){const slides=getSlides(),total=slides.length,slide=slides[state.currentSlide];if(!slide){state.screen="result";saveState();return render()}let content=slide.type==="material"?renderMaterialSlide(slide):slide.type==="image"?renderImageSlide(slide):slide.type==="video"?renderVideoSlide(slide):slide.type==="question"?renderQuestionSlide(slide):`<article class="material-card single"><div class="material-content"><div class="pill soft">ERROR</div><h2>Tipe slide tidak dikenali</h2><p>Tipe slide <code>${escapeHtml(slide.type)}</code> belum didukung.</p></div></article>`;const first=state.currentSlide===0,last=state.currentSlide===total-1,q=slide.type==="question",selected=q?state.answers[state.currentSlide]:undefined,canNext=!q||selected!==undefined;app.innerHTML=layout(`<section class="learning">${progress(state.currentSlide+1,total)}<div class="learning-meta"><span>SLIDE ${String(state.currentSlide+1).padStart(2,"0")} / ${String(total).padStart(2,"0")}</span><span>${escapeHtml(TRAINING.title)}</span></div>${content}<div class="nav-row"><button class="secondary" onclick="previousSlide()" ${first?"disabled":""}>← Sebelumnya</button><span class="nav-hint muted">${q?(selected===undefined?"Pilih salah satu jawaban.":"Jawaban sudah dipilih."):(last?"Training selesai.":"Lanjut ke slide berikutnya.")}</span><button class="primary" onclick="nextSlide()" ${!canNext?"disabled":""}>${last?"Lihat Hasil":"Berikutnya"} →</button></div></section>`)}
function renderMaterialSlide(s){const points=Array.isArray(s.points)?s.points:[];return `<article class="material-card"><div class="material-number">${String(state.currentSlide+1).padStart(2,"0")}</div><div class="material-content"><div class="pill soft">MATERI PEMBELAJARAN</div><h2>${escapeHtml(s.title||"")}</h2>${s.image?`<div class="material-image"><img src="${escapeHtml(s.image)}" alt="${escapeHtml(s.title||"Materi")}" onerror="this.parentElement.classList.add('image-error');this.style.display='none'"><div class="image-error-text">Gambar tidak dapat dimuat.</div></div>`:""}<p>${escapeHtml(s.text||"")}</p>${points.length?`<div class="points">${points.map(p=>`<div><span>✓</span>${escapeHtml(p)}</div>`).join("")}</div>`:""}</div></article>`}
function renderImageSlide(s){return `<article class="material-card single"><div class="material-content"><div class="pill soft">VISUAL / GRAFIK</div><h2>${escapeHtml(s.title||"")}</h2>${s.image?`<div class="graphic-image"><img src="${escapeHtml(s.image)}" alt="${escapeHtml(s.title||"Gambar training")}" onerror="this.parentElement.classList.add('image-error');this.style.display='none'"><div class="image-error-text">Gambar tidak dapat dimuat.</div></div>`:`<div class="image-placeholder">Gambar belum tersedia.</div>`}<p>${escapeHtml(s.text||"")}</p></div></article>`}
function renderVideoSlide(s){return `<article class="material-card single"><div class="material-content"><div class="pill soft">VIDEO PEMBELAJARAN</div><h2>${escapeHtml(s.title||"")}</h2><div class="video-card">${getVideoEmbed(s.video)}</div><p>${escapeHtml(s.text||"")}</p></div></article>`}
function renderQuestionSlide(s){const selected=state.answers[state.currentSlide];return `<article class="quiz-card"><div class="pill soft">PERTANYAAN</div><h2>${escapeHtml(s.q||"")}</h2><div class="options">${s.options.map((o,i)=>`<button class="option ${selected===i?"selected":""}" onclick="answerQuestion(${i})" type="button"><span>${String.fromCharCode(65+i)}</span><b>${escapeHtml(o)}</b></button>`).join("")}</div>${selected!==undefined?`<div class="answer-selected">✓ Jawaban kamu sudah dipilih.</div>`:""}</article>`}
function answerQuestion(i){state.answers[state.currentSlide]=i;saveState();renderLearning()}
function previousSlide(){if(state.currentSlide<=0)return;state.currentSlide--;saveState();renderLearning()}
function nextSlide(){const slides=getSlides(),current=slides[state.currentSlide];if(current&&current.type==="question"&&state.answers[state.currentSlide]===undefined)return;if(state.currentSlide<slides.length-1){state.currentSlide++;saveState();return renderLearning()}state.screen="result";saveState();render()}
function renderResult(){const r=calculateResult(),passed=r.passed;app.innerHTML=layout(`<section class="result-page"><div class="result-icon">${passed?"✓":"!"}</div><div class="pill">${passed?"TRAINING SELESAI":"BELUM LULUS"}</div><h2>${passed?"Selamat, training selesai.":"Training sudah selesai."}</h2><div class="score">${r.score}<small>/100</small></div><div class="result-status ${passed?"pass":"fail"}">${passed?"LULUS":"TIDAK LULUS"}</div><p class="muted">${escapeHtml(state.participant.name)}, kamu menjawab <b>${r.correct} dari ${r.total}</b> soal dengan benar.</p><div class="result-actions"><button class="primary" onclick="saveResult()" id="save-result-button">Simpan Hasil</button><button class="secondary" onclick="finishTraining()">Selesai</button></div><div id="save-status" class="save-status"></div></section>`)}
function finishTraining(){clearTrainingState();state.screen="home";state.currentSlide=0;state.answers={};state.participant={name:"",email:""};state.isSaving=false;render()}
const restored=loadState();if(restored)render();else{state.screen="home";render()}
