const TRAINING={title:"Learning and Development",subtitle:"Materi safe commuting awareness",duration:"10 Menit",slides:[
{type:"material",title:"Safe Commuting Awareness",text:"Safe commuting awareness dirancang untuk seluruh karyawan untuk selalu waspada terhadap risiko apapun.",image:"./assets/images/Slide2.PNG",points:["Laporkan kondisi yang tidak aman"]},
{type:"image",title:"Grafik Angka kecelakaan lalu lintas",text:"Berbagai kecelakaan kerja dapat terjadi karena kombinasi tindakan tidak aman dan kondisi lingkungan yang tidak aman. Memahami sumber risiko membantu kita melakukan pencegahan sejak awal.",image:"./assets/images/Slide3.PNG"},
{type:"video",title:"Video Pengenalan K3",text:"Silakan simak video berikut untuk memahami pentingnya keselamatan dan kesehatan kerja sebelum melanjutkan ke pertanyaan.",video:"https://www.youtube.com/watch?v=dQw4w9WgXcQ"},
{type:"question",q:"Apa tujuan utama penerapan K3?",options:["Mempercepat pekerjaan tanpa aturan","Menciptakan tempat kerja yang aman dan sehat","Mengurangi jumlah karyawan","Menghilangkan seluruh pekerjaan"],answer:1},
{type:"question",q:"Manakah yang merupakan contoh potensi bahaya?",options:["Area kerja tertata","APD sesuai standar","Kabel berserakan di jalur berjalan","Briefing keselamatan"],answer:2},
{type:"material",title:"Penggunaan Alat Pelindung Diri",text:"Alat Pelindung Diri atau APD digunakan sebagai perlindungan tambahan bagi pekerja dari risiko yang masih ada setelah pengendalian bahaya dilakukan.",image:"https://images.unsplash.com/photo-1581093458791-9d42e3c5f0b1?auto=format&fit=crop&w=1200&q=80",points:["Pilih APD sesuai risiko pekerjaan","Pastikan APD dalam kondisi layak","Gunakan APD dengan benar","Rawat dan simpan APD sesuai prosedur"]},
{type:"material",title:"Kenali Potensi Bahaya",text:"Potensi bahaya adalah kondisi atau tindakan yang dapat menyebabkan cedera, kerusakan, atau gangguan kesehatan. Bahaya dapat berasal dari lingkungan, peralatan, bahan, maupun perilaku manusia.",image:"https://images.unsplash.com/photo-1504307651254-35680f356dfd?auto=format&fit=crop&w=1200&q=80",points:["Amati kondisi area kerja","Identifikasi sumber bahaya","Nilai tingkat risikonya","Lakukan pengendalian yang sesuai"]},
{type:"question",q:"APD digunakan terutama untuk...",options:["Menambah gaya berpakaian","Memberikan perlindungan tambahan sesuai risiko","Menggantikan semua prosedur kerja","Mengurangi waktu istirahat"],answer:1},
{type:"question",q:"Sebelum menggunakan APD, kita sebaiknya...",options:["Memastikan kondisi APD layak digunakan","Langsung menggunakannya tanpa pemeriksaan","Meminjamkan kepada orang lain","Melepas bagian pengaman APD"],answer:0},
{type:"question",q:"Jika menemukan kondisi tidak aman, tindakan yang tepat adalah...",options:["Membiarkannya","Menunggu sampai terjadi kecelakaan","Melaporkan dan melakukan pengendalian sesuai prosedur","Mengabaikannya"],answer:2},
{type:"material",title:"Identifikasi Bahaya",text:"Identifikasi bahaya dilakukan untuk mengetahui sumber bahaya yang dapat menyebabkan kecelakaan atau gangguan kesehatan. Proses ini merupakan bagian penting dalam pengendalian risiko.",image:"https://images.unsplash.com/photo-1504917595217-d4dc5ebe6122?auto=format&fit=crop&w=1200&q=80",points:["Periksa kondisi lingkungan kerja","Periksa peralatan dan mesin","Perhatikan aktivitas pekerja","Catat potensi bahaya yang ditemukan"]},
{type:"material",title:"Pengendalian Risiko",text:"Setelah bahaya diidentifikasi, langkah berikutnya adalah melakukan pengendalian untuk mengurangi kemungkinan terjadinya kecelakaan atau dampak kesehatan.",image:"https://images.unsplash.com/photo-1586864387967-d02ef85d93e8?auto=format&fit=crop&w=1200&q=80",points:["Hilangkan sumber bahaya jika memungkinkan","Gunakan pengendalian teknis","Gunakan prosedur kerja yang aman","Gunakan APD sebagai perlindungan tambahan"]},
{type:"question",q:"Apa langkah awal dalam proses pengendalian risiko?",options:["Mengidentifikasi bahaya","Mengabaikan risiko","Menghentikan seluruh pekerjaan","Membuat laporan keuangan"],answer:0},
{type:"question",q:"Mengapa risiko di tempat kerja perlu dikendalikan?",options:["Agar pekerjaan menjadi lebih lama","Untuk mencegah kejadian yang tidak diinginkan","Untuk menambah pekerjaan","Agar terlihat sibuk"],answer:1},
{type:"question",q:"Apa tindakan yang tepat ketika melihat kondisi berbahaya?",options:["Membiarkannya","Melaporkan dan melakukan tindakan pengendalian","Menunggu orang lain","Mengabaikannya"],answer:1}
]};
